language: ruby
rvm:
  - "2.2.5"
  - "2.3.2"
sudo: false
addons:
  code_climate:
    repo_token: "3fa15641f89d7fce5dde29b03abaa3a07225b6f1509b3046cdbf4c64e22619f4"
after_success:
  - bundle exec codeclimate-test-reporter
